using Microsoft.Xna.Framework.Input;

namespace GlobalTypes.InputManagement
{
    public enum KeyPhase
    {
        Press,
        Hold,
        Release
    }

    public enum Key
    {
        None = Keys.None,
        Back = Keys.Back,
        Tab = Keys.Tab,
        Enter = Keys.Enter,
        CapsLock = Keys.CapsLock,
        Escape = Keys.Escape,
        Space = Keys.Space,
        PageUp = Keys.PageUp,
        PageDown = Keys.PageDown,
        End = Keys.End,
        Home = Keys.Home,
        Left = Keys.Left,
        Up = Keys.Up,
        Right = Keys.Right,
        Down = Keys.Down,
        Select = Keys.Select,
        Print = Keys.Print,
        Execute = Keys.Execute,
        PrintScreen = Keys.PrintScreen,
        Insert = Keys.Insert,
        Delete = Keys.Delete,
        Help = Keys.Help,
        D0 = Keys.D0,
        D1 = Keys.D1,
        D2 = Keys.D2,
        D3 = Keys.D3,
        D4 = Keys.D4,
        D5 = Keys.D5,
        D6 = Keys.D6,
        D7 = Keys.D7,
        D8 = Keys.D8,
        D9 = Keys.D9,
        A = Keys.A,
        B = Keys.B,
        C = Keys.C,
        D = Keys.D,
        E = Keys.E,
        F = Keys.F,
        G = Keys.G,
        H = Keys.H,
        I = Keys.I,
        J = Keys.J,
        K = Keys.K,
        L = Keys.L,
        M = Keys.M,
        N = Keys.N,
        O = Keys.O,
        P = Keys.P,
        Q = Keys.Q,
        R = Keys.R,
        S = Keys.S,
        T = Keys.T,
        U = Keys.U,
        V = Keys.V,
        W = Keys.W,
        X = Keys.X,
        Y = Keys.Y,
        Z = Keys.Z,
        LeftWindows = Keys.LeftWindows,
        RightWindows = Keys.RightWindows,
        Apps = Keys.Apps,
        Sleep = Keys.Sleep,
        NumPad0 = Keys.NumPad0,
        NumPad1 = Keys.NumPad1,
        NumPad2 = Keys.NumPad2,
        NumPad3 = Keys.NumPad3,
        NumPad4 = Keys.NumPad4,
        NumPad5 = Keys.NumPad5,
        NumPad6 = Keys.NumPad6,
        NumPad7 = Keys.NumPad7,
        NumPad8 = Keys.NumPad8,
        NumPad9 = Keys.NumPad9,
        Multiply = Keys.Multiply,
        Add = Keys.Add,
        Separator = Keys.Separator,
        Subtract = Keys.Subtract,
        Decimal = Keys.Decimal,
        Divide = Keys.Divide,
        F1 = Keys.F1,
        F2 = Keys.F2,
        F3 = Keys.F3,
        F4 = Keys.F4,
        F5 = Keys.F5,
        F6 = Keys.F6,
        F7 = Keys.F7,
        F8 = Keys.F8,
        F9 = Keys.F9,
        F10 = Keys.F10,
        F11 = Keys.F11,
        F12 = Keys.F12,
        F13 = Keys.F13,
        F14 = Keys.F14,
        F15 = Keys.F15,
        F16 = Keys.F16,
        F17 = Keys.F17,
        F18 = Keys.F18,
        F19 = Keys.F19,
        F20 = Keys.F20,
        F21 = Keys.F21,
        F22 = Keys.F22,
        F23 = Keys.F23,
        F24 = Keys.F24,
        NumLock = Keys.NumLock,
        Scroll = Keys.Scroll,
        LeftShift = Keys.LeftShift,
        RightShift = Keys.RightShift,
        LeftControl = Keys.LeftControl,
        RightControl = Keys.RightControl,
        LeftAlt = Keys.LeftAlt,
        RightAlt = Keys.RightAlt,
        BrowserBack = Keys.BrowserBack,
        BrowserForward = Keys.BrowserForward,
        BrowserRefresh = Keys.BrowserRefresh,
        BrowserStop = Keys.BrowserStop,
        BrowserSearch = Keys.BrowserSearch,
        BrowserFavorites = Keys.BrowserFavorites,
        BrowserHome = Keys.BrowserHome,
        VolumeMute = Keys.VolumeMute,
        VolumeDown = Keys.VolumeDown,
        VolumeUp = Keys.VolumeUp,
        MediaNextTrack = Keys.MediaNextTrack,
        MediaPreviousTrack = Keys.MediaPreviousTrack,
        MediaStop = Keys.MediaStop,
        MediaPlayPause = Keys.MediaPlayPause,
        LaunchMail = Keys.LaunchMail,
        SelectMedia = Keys.SelectMedia,
        LaunchApplication1 = Keys.LaunchApplication1,
        LaunchApplication2 = Keys.LaunchApplication2,
        OemSemicolon = Keys.OemSemicolon,
        OemPlus = Keys.OemPlus,
        OemComma = Keys.OemComma,
        OemMinus = Keys.OemMinus,
        OemPeriod = Keys.OemPeriod,
        OemQuestion = Keys.OemQuestion,
        OemTilde = Keys.OemTilde,
        OemOpenBrackets = Keys.OemOpenBrackets,
        OemPipe = Keys.OemPipe,
        OemCloseBrackets = Keys.OemCloseBrackets,
        OemQuotes = Keys.OemQuotes,
        Oem8 = Keys.Oem8,
        OemBackslash = Keys.OemBackslash,
        ProcessKey = Keys.ProcessKey,
        Attn = Keys.Attn,
        Crsel = Keys.Crsel,
        Exsel = Keys.Exsel,
        EraseEof = Keys.EraseEof,
        Play = Keys.Play,
        Zoom = Keys.Zoom,
        Pa1 = Keys.Pa1,
        OemClear = Keys.OemClear,
        ChatPadGreen = Keys.ChatPadGreen,
        ChatPadOrange = Keys.ChatPadOrange,
        Pause = Keys.Pause,
        ImeConvert = Keys.ImeConvert,
        ImeNoConvert = Keys.ImeNoConvert,
        Kana = Keys.Kana,
        Kanji = Keys.Kanji,
        OemAuto = Keys.OemAuto,
        OemCopy = Keys.OemCopy,
        OemEnlW = Keys.OemEnlW,

        MouseLeft = 1000,
        MouseRight,
        MouseMiddle,
        MouseXButton1,
        MouseXButton2
    }
}